# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 154114a008d628669e11a02f154a3777848e460426402edd23ad35edcb20fa7de008be0dbc089ebcfe387cea9be23828588144cd97d5adab888cc5d8410d7c8b

test:
  secret_key_base: 35ceeec388dbd662a81c928d9033ab638b1442fa4bf03392e66d22b2fba7ce331599034c866df9a78dfe5afb56b3d75ed902974805231b4da62cdb6f3f872696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
